const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('remoteCodex', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  onStatus: (callback) => ipcRenderer.on('status', (_, value) => callback(value)),
  getLog: () => ipcRenderer.invoke('get-log'),
  openLog: () => ipcRenderer.invoke('open-log'),
  onLog: (callback) => ipcRenderer.on('log-entry', (_, value) => callback(value)),
  getAgentState: () => ipcRenderer.invoke('get-agent-state'),
  getRelayConfig: () => ipcRenderer.invoke('get-relay-config'),
  loadRelayConfigFile: (filePath) => ipcRenderer.invoke('load-relay-config-file', filePath),
  exportRelayConfig: () => ipcRenderer.invoke('export-relay-config'),
  testRelayConfig: (value) => ipcRenderer.invoke('test-relay-config', value),
  saveRelayConfig: (value) => ipcRenderer.invoke('save-relay-config', value),
  setDeviceAlias: (value) => ipcRenderer.invoke('set-device-alias', value),
  setWorkspace: (value) => ipcRenderer.invoke('set-workspace', value),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  onWorkspace: (callback) => ipcRenderer.on('workspace', (_, value) => callback(value)),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_, value) => callback(value)),
  startRdp: (ttlSeconds) => ipcRenderer.invoke('start-rdp', ttlSeconds),
  stopRdp: () => ipcRenderer.invoke('stop-rdp'),
  terminateTaskTree: () => ipcRenderer.invoke('terminate-task-tree'),
  onRdpStatus: (callback) => ipcRenderer.on('rdp-status', (_, value) => callback(value)),
  setComputerUseEnabled: (enabled) => ipcRenderer.invoke('set-computer-use-enabled', enabled),
  onComputerUseStatus: (callback) => ipcRenderer.on('computer-use-status', (_, value) => callback(value)),
});
